#%RAML 1.0 Trait

responses:
      "200":
        body:
          properties:
            message:
              example: Example
              type: string
            status:
              example: Example
              type: string